### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by awenelo** [pokeimon/OctoPrint-ESPurnaRGB#2]
@pokeimon, I notice that there has been no update on Python 3 compatibility since a request was made for compatibility in early October (#1). If you are not able to find the time/are no longer interested in maintaining this plugin, should this plugin be marked as abandoned?

**Comment by pokeimon** [comment]
Sorry for the delay.
Issue #1  has been addressed with the latest release v1.1.0.
